-- to insert some values into the webpage you could just do it through the webpage with the add button or copy and paste the following code
-- IMPORTANT: to run all of this code you first have to make a new database in postgres and call it zaBooks
-- My ass did not test this and tbh i dont want to so if it doesnt work you can just copy the values and insert it into the add page

CREATE TABLE books (
    isbn TEXT,
    title TEXT,
    dateread DATE,
    review INTEGER,
    id SERIAL PRIMARY KEY,
    text TEXT,
    author text
);

INSERT INTO books (isbn, title, dateread, review, author, text)
VALUES ('9780307275639', 'Tuesdays with Morrie', '2024-07-28', 83, "Tuesdays with Morrie by Mitch Albom is a touching memoir that offers profound insights into life, love, work, and death through the lens of a unique student-teacher relationship. The book chronicles the author's meetings with his former sociology professor, Morrie Schwartz, who is dying from ALS (Lou Gehrig's disease). Albom, feeling lost and disconnected from his life as a successful sportswriter, reconnects with Morrie after seeing him on a TV interview. What starts as a one-time visit turns into a series of weekly meetings, each offering a different lesson on life. These meetings, held on Tuesdays, become a space for deep conversation and reflection, and Albom records these lessons with great sensitivity and honesty. Morrie's wisdom is simple yet profound. His perspective on living a meaningful life, embracing emotions, and building authentic relationships is both timeless and timely. The book is filled with poignant anecdotes, thought-provoking dialogues, and moments of profound truth that resonate long after the last page is turned. One of the strengths of Tuesdays with Morrie is its ability to convey deep, philosophical ideas in an accessible and relatable way. Albom's writing is straightforward but evocative, capturing the essence of Morrie's teachings without overcomplicating them. The relationship between Albom and Morrie is the heart of the book, and their bond is beautifully portrayed, highlighting the transformative power of mentorship and friendship. Overall, Tuesdays with Morrie is a heartfelt and inspiring read. It encourages readers to reflect on their own lives and consider what truly matters. It's a book that can be revisited time and again, with each reading offering new insights and reminders of the importance of living with intention and compassion. Whether you're seeking guidance, comfort, or simply a good story, Tuesdays with Morrie is a timeless treasure that delivers on all fronts.");

INSERT INTO books (isbn, title, dateread, review, author, text)
VALUES ('9783060311354', 'Fahrenheit 451', '2023-06-25', 89, 'Ray Bradbury', "Ray Bradbury's Fahrenheit 451 is a timeless classic that delves into the perils of a dystopian society obsessed with censorship, conformity, and anti-intellectualism. Set in a future where books are banned, and firemen burn them, the novel follows Guy Montag, a fireman who becomes disillusioned with his oppressive society. Montag's transformation begins when he meets Clarisse, a young woman whose curiosity and free-spirited nature ignite his own quest for knowledge and self-discovery. Bradbury's exploration of censorship and the suppression of dissenting ideas serves as a powerful warning about the dangers of homogenizing culture. His critique of over-reliance on technology and superficial media consumption resonates deeply, highlighting how these can lead to a disengaged and unthinking populace. Montag's journey from compliance to a passionate seeker of truth is portrayed with depth and nuance, making him a compelling and relatable character. The novel's vivid imagery and symbolism, such as the mechanical hound and the omnipresent parlour walls, effectively convey the oppressive nature of Montag's society and his quest for enlightenment. Bradbury's poetic yet precise writing style enhances the reader's immersion in the story, offering both a captivating narrative and profound insights. The themes of intellectual freedom and the importance of independent thought are woven seamlessly into the plot, making the novel both engaging and thought-provoking. Despite being written over 70 years ago, Fahrenheit 451 remains strikingly relevant today. In an era of instantaneous information and media saturation, the novel prompts readers to reflect on how these factors influence our understanding of the world. Debates over free speech and media influence are more intense than ever, underscoring the enduring significance of Bradbury's themes. In summary, Fahrenheit 451 is a masterful work of speculative fiction that challenges readers to consider the value of knowledge, the dangers of censorship, and the importance of critical thinking. Bradbury's vision of a dystopian future is chilling and thought-provoking, making the novel an essential read for anyone concerned with the preservation of intellectual freedom and the human spirit. Its enduring relevance and powerful message ensure it remains a must-read for generations to come.");

